### ISSUE TITLE
Getting standard 401 on /private

### ISSUE THREAD

**Issue by individual11** [SeptiyanAndika/serverless-custom-authorizer#1]
Not seeing anything custom that can be invoked. Brought it down and ran as-is.

**Comment by habibqureshi** [comment]
{
    "statusCode": 403,
    "error": "Forbidden",
    "message": "User is not authorized to access this resource"
}

getting this response, your solution is not working,

**Comment by agungalteacare** [comment]
@habibqureshi , its working if you run on cloud. if you running with serverless-offline, it will show default error.
